### ISSUE TITLE
New contributivity method : 'federated step-by-step increments' 

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#105]
**Main idea** : measure the performance increments on the global validation dataset after every minibatch training.
When the whole federated training is done, average for every node the performance increments, this should give an estimate on how the model improved on every node, and thus might be an estimate of the contributivity of every node/dataset !

**Some technical considerations:**

- Increments from the first minibatches might be huge and not really relevant --> we should discard the X first increment. Or another option would be to only use the performance increments when the model has a performance of a least 50% (50 is an example).
- Increments from the last minibatches (just before the earlystopping) might be very noisy and therefore not relevant --> we could discard the X last increments.
- This approach might not be feasible when doing _sequential_ FL --> For instance, if we train node_1, then node_2, then node_3, it might be easier for node_1 to have a big increment because it starts first compared to node 3.

Note this approach can also be a cheap baseline for more advanced contributivity methods, in order to sample/discard specific nodes.

**Comment by jeromechambost** [comment]
**In federated averaging computation:**

For each computation round:
- Performance of newly fit partner model on global test dataset is computed and stored for each partner
- Performance of aggregated model on global dataset is computed and stored

![Step-by-step performance increment](https://user-images.githubusercontent.com/58439042/81797162-b52e1b80-950e-11ea-9042-83becddb8a06.png)

At the end of computation, matrix of performance is stored with C rows (C = number of computation rounds) and N+1 columns (N = number of partners)

New matrix of performance increase is computed: For each computation round, increase in performance is calculated between newly fit model for each partner and previous aggregated model

Contributivity of partner is a function of the matrix of performance increase:
Contributivity funtion can be:
- Average of increase of performance
- Weighted average of increase of performance (increasing weights with increasing number of computation rounds)

Contributivity function takes 3 parameters:
- X the proportion of first computation rounds that are discarded due to high and uneven performance increase
- Y the proportion of last computation rounds that are discarded due to noise 

Further considerations
Performance is set to be accuracy but can be changed to another metric (if we choose the metric to be loss, we need to change calculation to adapt to the loss decrease instead of performance increase)

**Comment by bowni** [comment]
I think we have some of what we need to move forward on this now that we merged PR #141.

At the end of a multi-partner computation, we have:

- `score_matrix_per_partner` for the individual partner's models, with the perf. on validation data for each epoch > each mini-batch > each partner. In the above schema this corresponds to `P(k, 1)`, `P(k, 2)`, `P(k, 3)`
- `score_matrix_collective_models` for the collective models, with the perf. on validation data for each epoch > each mini-batch. In the above schema this corresponds to `P(k)`

So we can easily process the differences `P(k) - P(k, <partner_id>)`.

For the X and Y proportions above I haven't thought about it yet. What do you think @jeromechambost @RomainGoussault @Thomas-Galtier?

**Comment by jeromechambost** [comment]
Until now we had implicitly assumed that at each computation round, at least one model trained independently on one partner data had a validation score that increased compared to the collective model of the previous round. 

In reality this is not necessarily true. We find situations (for examples when partners all have exclusive data targets) where for each computation round, the individual performance of each partner is lower than the performance of the collective model from the previous round - despite the collective model performance continuously increasing

We need to find a general way of regularizing the contributivities to adapt to the situations where they can take negative or positive values.

Two possibilities are considered:
- standard regularization: 
At each computation round, the minimum contributivity value is retrieved
This regularization gives accurate results in most situations. In some cases, it leads to one partner contributivity to 0 (one partner always has the lowest global validation score on the newly trained model, and this score is lower than the global validation score from the previous collective model)

- Relative regularization
At each computation round, the contributivity for each partner is calculated as the ratio between the validation score of the newly trained model for each partner and the validation score from the previously trained collective model
This regularization apparently gives accurate results in all situations
